### ISSUE TITLE
History should get displayed in reverse order.

### ISSUE THREAD

**Issue by Vishesh-Pandey** [Vishesh-Pandey/rapid-whatsapp#7] opened 2023-05-05 14:33 UTC
So the number on which we texted last time should appear on the top. 
As of now, the oldest number is getting displayed on top and the latest one at the very end. 
We need to reverse it and display

**Comment by MZHoffman** [comment] 2023-05-05 16:08
I have done it. Please assign to me. The problem is I get some Conflicts when I did pull request. Not sure what it is.

**Comment by MZHoffman** [comment] 2023-05-05 20:33
Now it's fixed: https://github.com/MZHoffman/rapid-whatsapp/pull/1

Can you assign task to me?

**Closed** 2023-05-06 17:08 UTC
Labels: enhancement, help wanted, good first issue
